wandb_version: 1

base_size:
  value: 0.005
baseline_mode:
  value: 1
grid_percentage:
  value: 0.5
grid_spacing_type:
  value: 1
grid_step:
  value: 200
martingale_start_level:
  value: 3
max_floating_loss:
  value: 100
max_levels:
  value: 8
max_position_value:
  value: 1000
multiplier:
  value: 2.5
per_trade_profit:
  value: 3
take_profit_mode:
  value: 0
target_profit:
  value: 30
total_capital:
  value: 10000
