wandb_version: 1

base_size:
  value: 0.005
baseline_mode:
  value: 1
grid_percentage:
  value: 1
grid_spacing_type:
  value: 0
grid_step:
  value: 300
martingale_start_level:
  value: 3
max_floating_loss:
  value: 150
max_levels:
  value: 5
max_position_value:
  value: 500
multiplier:
  value: 2.5
per_trade_profit:
  value: 10
take_profit_mode:
  value: 1
target_profit:
  value: 10
total_capital:
  value: 10000
